services:
  - type: web
    runtime: static
    name: devet-frontend
    repo: https://github.com/RiccardoSoroImola/devet_frontend
    branch: main
    rootDir: .
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter ./apps/web... run build && pnpm --filter ./apps/web... run export
    staticPublishPath: apps/web/out
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://devet-backend.onrender.com

  - type: web
    name: devet-backend
    repo: https://github.com/RiccardoSoroImola/devet_frontend
    branch: main
    env: node
    rootDir: .
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter ./apps/api... run build
    startCommand: pnpm --filter ./apps/api... run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
